.\" Copyright (C) 2026 Christoph Hellwig <hch@lst.de>
.\"
.\" SPDX-License-Identifier: LGPL-2.0-or-later
.\"
.TH io_uring_prep_cmd_zone_reset_all 3 "Aug 11, 2026" "liburing-2.16" "liburing Manual"
.SH NAME
io_uring_prep_cmd_zone_reset_all \- prepare a zone_reset_all command
.SH SYNOPSIS
.nf
.B #include <liburing.h>
.PP
.BI "void io_uring_prep_cmd_zone_reset_all(struct io_uring_sqe *" sqe ", int " fd ");"
.fi
.SH DESCRIPTION
The
.BR io_uring_prep_cmd_zone_reset_all (3)
function prepares a zone_reset_all command request. The submission queue entry
.I sqe
is setup to reset all sequential write required zones on the block device
pointed to by
.IR fd .

This command does not synchronize against concurrent file operations, including
but not limited to reads, write, ioctls and other uring_cmds and only performs
a best effort invalidation of the page cache for the device.  The user has
to make sure that no other in-flight requests are modifying or reading the
range(s). If that is the case, it might result in stale page cache and data
inconsistencies.

Available since Linux 7.TBD.

.SH RETURN VALUE
None
.SH ERRORS
The CQE
.I res
field will contain the result of the operation. On success, this field will be
set to
.B 0 .
On error, a negative error value is returned. Note that where synchronous
system calls will return
.B -1
on failure and set
.I errno
to the actual error value, io_uring never uses
.IR errno .
Instead it returns the negated
.I errno
directly in the CQE
.I res
field.
.SH SEE ALSO
.BR io_uring_get_sqe (3),
.BR io_uring_submit (3),
