.\" Copyright (C) 2022 Stefan Roesch <shr@devkernel.io>
.\"
.\" SPDX-License-Identifier: LGPL-2.0-or-later
.\"
.TH io_uring_unregister_napi 3 "November 16, 2022" "liburing-2.4" "liburing Manual"
.SH NAME
io_uring_unregister_napi \- unregister NAPI busy poll settings
.SH SYNOPSIS
.nf
.B #include <liburing.h>
.PP
.BI "int io_uring_unregister_napi(struct io_uring *" ring ","
.BI "                             struct io_uring_napi *" napi)
.PP
.fi
.SH DESCRIPTION
.PP
The
.BR io_uring_unregister_napi (3)
function unregisters the NAPI busy poll settings for subsequent operations.

.SH RETURN VALUE
On success
.BR io_uring_unregister_napi (3)
return 0. On failure they return
.BR -errno .
It also updates the napi structure with the current values.
